//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Downloader_Common.PrefillDataDownloaderWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PrefillDataDownloaderSoap", Namespace="http://localhost/DigitalPen/PrefillDataDownloaderService")]
    public partial class PrefillDataDownloader : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetManifestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetManifestDownloadedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXfdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPdfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PrefillDataDownloader() {
            this.Url = "http://localhost/DigitalPen/PrefillDataDownloaderService/PrefillDataDownloader.as" +
                "mx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetManifestCompletedEventHandler GetManifestCompleted;
        
        /// <remarks/>
        public event SetManifestDownloadedCompletedEventHandler SetManifestDownloadedCompleted;
        
        /// <remarks/>
        public event GetXfdfCompletedEventHandler GetXfdfCompleted;
        
        /// <remarks/>
        public event GetPdfCompletedEventHandler GetPdfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/DigitalPen/PrefillDataDownloaderService/GetManifest", RequestNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", ResponseNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetManifest(string customerCode, string siteCode, int manifestNumber) {
            object[] results = this.Invoke("GetManifest", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetManifest(string customerCode, string siteCode, int manifestNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetManifest", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndGetManifest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetManifestAsync(string customerCode, string siteCode, int manifestNumber) {
            this.GetManifestAsync(customerCode, siteCode, manifestNumber, null);
        }
        
        /// <remarks/>
        public void GetManifestAsync(string customerCode, string siteCode, int manifestNumber, object userState) {
            if ((this.GetManifestOperationCompleted == null)) {
                this.GetManifestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManifestOperationCompleted);
            }
            this.InvokeAsync("GetManifest", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber}, this.GetManifestOperationCompleted, userState);
        }
        
        private void OnGetManifestOperationCompleted(object arg) {
            if ((this.GetManifestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManifestCompleted(this, new GetManifestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/DigitalPen/PrefillDataDownloaderService/SetManifestDownloaded", RequestNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", ResponseNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetManifestDownloaded(string customerCode, string siteCode, int manifestNumber) {
            object[] results = this.Invoke("SetManifestDownloaded", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetManifestDownloaded(string customerCode, string siteCode, int manifestNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetManifestDownloaded", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSetManifestDownloaded(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetManifestDownloadedAsync(string customerCode, string siteCode, int manifestNumber) {
            this.SetManifestDownloadedAsync(customerCode, siteCode, manifestNumber, null);
        }
        
        /// <remarks/>
        public void SetManifestDownloadedAsync(string customerCode, string siteCode, int manifestNumber, object userState) {
            if ((this.SetManifestDownloadedOperationCompleted == null)) {
                this.SetManifestDownloadedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetManifestDownloadedOperationCompleted);
            }
            this.InvokeAsync("SetManifestDownloaded", new object[] {
                        customerCode,
                        siteCode,
                        manifestNumber}, this.SetManifestDownloadedOperationCompleted, userState);
        }
        
        private void OnSetManifestDownloadedOperationCompleted(object arg) {
            if ((this.SetManifestDownloadedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetManifestDownloadedCompleted(this, new SetManifestDownloadedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/DigitalPen/PrefillDataDownloaderService/GetXfdf", RequestNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", ResponseNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetXfdf(string customerCode, string siteCode, string formInstanceId) {
            object[] results = this.Invoke("GetXfdf", new object[] {
                        customerCode,
                        siteCode,
                        formInstanceId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetXfdf(string customerCode, string siteCode, string formInstanceId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetXfdf", new object[] {
                        customerCode,
                        siteCode,
                        formInstanceId}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndGetXfdf(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetXfdfAsync(string customerCode, string siteCode, string formInstanceId) {
            this.GetXfdfAsync(customerCode, siteCode, formInstanceId, null);
        }
        
        /// <remarks/>
        public void GetXfdfAsync(string customerCode, string siteCode, string formInstanceId, object userState) {
            if ((this.GetXfdfOperationCompleted == null)) {
                this.GetXfdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXfdfOperationCompleted);
            }
            this.InvokeAsync("GetXfdf", new object[] {
                        customerCode,
                        siteCode,
                        formInstanceId}, this.GetXfdfOperationCompleted, userState);
        }
        
        private void OnGetXfdfOperationCompleted(object arg) {
            if ((this.GetXfdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXfdfCompleted(this, new GetXfdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/DigitalPen/PrefillDataDownloaderService/GetPdf", RequestNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", ResponseNamespace="http://localhost/DigitalPen/PrefillDataDownloaderService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPdf(string customerCode, string siteCode, string formId) {
            object[] results = this.Invoke("GetPdf", new object[] {
                        customerCode,
                        siteCode,
                        formId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPdf(string customerCode, string siteCode, string formId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPdf", new object[] {
                        customerCode,
                        siteCode,
                        formId}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndGetPdf(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPdfAsync(string customerCode, string siteCode, string formId) {
            this.GetPdfAsync(customerCode, siteCode, formId, null);
        }
        
        /// <remarks/>
        public void GetPdfAsync(string customerCode, string siteCode, string formId, object userState) {
            if ((this.GetPdfOperationCompleted == null)) {
                this.GetPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPdfOperationCompleted);
            }
            this.InvokeAsync("GetPdf", new object[] {
                        customerCode,
                        siteCode,
                        formId}, this.GetPdfOperationCompleted, userState);
        }
        
        private void OnGetPdfOperationCompleted(object arg) {
            if ((this.GetPdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPdfCompleted(this, new GetPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetManifestCompletedEventHandler(object sender, GetManifestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManifestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManifestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetManifestDownloadedCompletedEventHandler(object sender, SetManifestDownloadedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetManifestDownloadedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetManifestDownloadedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetXfdfCompletedEventHandler(object sender, GetXfdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXfdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXfdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPdfCompletedEventHandler(object sender, GetPdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591